/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.BillDAO;
import dao.CustomerDAO;
import dao.DigitalwalletDAO;
import java.util.ArrayList;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import model.Bill;
import model.Customer;
import model.Digitalwallet;
import model.User;

/**
 *
 * @author PT-LS
 */
public class DigitalwalletFrm extends javax.swing.JFrame {
    private User user;
    private int value;
    private Digitalwallet searchDigitalWalletbyIDcustomer;
    /**
     * Creates new form DigitalwalletFrm
     */
    public DigitalwalletFrm(User user , int value) {
        this.user = user;
        this.value = value;
        initComponents();
        searchDigitalWalletbyIDcustomer = new DigitalwalletDAO().searchDigitalWalletbyIDcustomer(value);
        wl1.setText(searchDigitalWalletbyIDcustomer.getIdwallet()+"");
        wl2.setText(searchDigitalWalletbyIDcustomer.getIdcustomer()+"");
        wl3.setText(searchDigitalWalletbyIDcustomer.getIdRank()+"");
        wl4.setText(searchDigitalWalletbyIDcustomer.getMoneyaccumulated()+"");
    }

    private DigitalwalletFrm() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        wl2 = new javax.swing.JLabel();
        wl3 = new javax.swing.JLabel();
        wl4 = new javax.swing.JLabel();
        wl1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã tài khoản");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Ví điện tử");

        jLabel3.setText("Mã khách hàng");

        jLabel4.setText("Mức độ ưu tiên");

        jLabel5.setText("Sô tiền trong tài khoản");

        wl2.setText("jLabel7");

        wl3.setText("jLabel8");

        wl4.setText("jLabel9");

        wl1.setText(" ");

        jButton1.setText("Thanh toan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Quay lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(wl2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(wl1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(wl3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(wl4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jButton1)
                        .addGap(27, 27, 27)
                        .addComponent(jButton2)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(wl1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(wl2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(wl3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(wl4))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         (new ChosePayment(user,value)).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String paymentType = "Vi dien tu";
        
        ArrayList<Bill> searchBillByIdCustomer2 = new BillDAO().searchBillByIdCustomer(value);
        boolean kt = false,kt2=false;
        
        for (Bill searchBillByIdCustomer21 : searchBillByIdCustomer2) {
            if(searchBillByIdCustomer21.getPaymentType().length()>0) kt=true;
            if(searchDigitalWalletbyIDcustomer.getMoneyaccumulated()>=searchBillByIdCustomer21.getAmount() && searchDigitalWalletbyIDcustomer.getMoneyaccumulated()>0) kt2=true;
        }
        if(kt==false&&kt2==true){
        boolean updateBill = new BillDAO().updateBill(value, paymentType);
        boolean updateDigital = new DigitalwalletDAO().updateDigital(searchDigitalWalletbyIDcustomer.getIdwallet(),searchDigitalWalletbyIDcustomer.getMoneyaccumulated()-searchBillByIdCustomer2.get(0).getAmount());
        ArrayList<Bill> searchBillByIdCustomer = new BillDAO().searchBillByIdCustomer(value);
        
        Properties pro = System.getProperties();
        pro.put("mail.smtp.host", "smtp.gmail.com");
        pro.put("mail.smtp.port", "465");
        pro.put("mail.smtp.auth", "true");
        pro.put("mail.smtp.socketFactory.port", "465");
        pro.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");

        
        Session session = Session.getInstance(pro, new javax.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication("leanhtung20299@gmail.com", "b3k0jl0v3");
            }
        });
        Customer searchCustomerbyID = new CustomerDAO().searchCustomerbyID(value);
        try {
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress("leanhtung20299@gmail.com"));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(searchCustomerbyID.getEmail()));
            message.setSubject("Hoa Don thanh toan-"+searchCustomerbyID.getEmail());
            for (Bill searchBillByIdCustomer1 : searchBillByIdCustomer) {
                message.setText("Khach hang "+searchCustomerbyID.getName()+"da thanh toan : " + searchBillByIdCustomer1.getPaymentType() +"tong tien"+searchBillByIdCustomer1.getAmount());
            }
               
            Transport.send(message);

        } catch (MessagingException ex) {
            ex.printStackTrace();
        }

//        if(updateBill) {
        JOptionPane.showMessageDialog(this, "Thanh toán thành công bằng hình ví điện tử");
        (new SearchCustomerFrm(user)).setVisible(true);
        this.dispose();
        }
        else JOptionPane.showMessageDialog(this, "Không đủ tiền để thanh toán");
//        }
//        else  JOptionPane.showMessageDialog(this, "Thanh toán thất bại");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DigitalwalletFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DigitalwalletFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DigitalwalletFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DigitalwalletFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DigitalwalletFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel wl1;
    private javax.swing.JLabel wl2;
    private javax.swing.JLabel wl3;
    private javax.swing.JLabel wl4;
    // End of variables declaration//GEN-END:variables
}
